### ISSUE TITLE
继续加油

### ISSUE THREAD

**Issue by wy2022** [fancy-components/fancy-components#2]
加油多搞点组件库

**Comment by MaidSG** [comment]
大佬能不能发一下演示页面的vue项目啊,不是很会用组件

**Comment by fancy-components** [comment]
> 大佬能不能发一下演示页面的vue项目啊,不是很会用组件

先别急 我们团队正在打算重构这个项目
先会打造一个用 vue 语法写 web-components 的编译器
这样就能够用到 vue 的模板语法来生成高性能的 render 函数
然后在这个编译器脚手架中重构 fancy-components 这个组件库
到时候会封装的更加全面一点 类似于 element-ui 的那种 但组件会比它更加丰富 会有很多花里胡哨很好玩的组件
然后下一步就是再根据 Vue 和 React 的语法进一步封装 让 Vue React 项目能够开箱即用
最后一步便是完善文档
由于工作量比较大 所以不会在近期内完成 但我们会尽可能的加快速度 敬请期待～
