### ISSUE TITLE
Tiny Flags

### ISSUE THREAD

**Issue by matiasbontempo** [fancy-components/fancy-components#5]
Hi! Sorry to create this ticket but I couldn't find any other way to reach you.
I'm developing a lib and extension that allows users to set and update feature flags.

I was hoping I could borrow the `tiny-flags` npm package from you. I saw it's empty and it has not been updated in a couple of years and I already did some branding with the `Tiny Flags` name.

Feel free to reach out to me in Twitter ([@matiasbontempo](https://twitter.com/matiasbontempo)) or by email ([matias.bontempo@gmail.com](mailto:matias.bontempo@gmail.com)).

**Comment by fancy-components** [comment]
OK
I will watching your reply
When you say: "I'm already!"
I will delete this package immediately
After 24 hours term of protection
You could register **tiny-flags** package

**Comment by matiasbontempo** [comment]
That is great news! I'm ready when you are.

Thanks! I really appreciate this.

**Comment by fancy-components** [comment]
I'm already deleted is at Washington time 1: 07 am
You can use it in New Year
Happy New Year 🎉

**Comment by matiasbontempo** [comment]
Haha! Thanks! 🇦🇷🇦🇷🇦🇷
I'll let you know once I'm able to push the new package.

Happy New Year to you too! 🎉 I owe you one
